[workspace]
members = [
    "contracts/whirlwind-swap",
    "packages/lib",
]

[workspace.dependencies]
cosmwasm-bignumber = "2.2.0"
cw2 = "1.0.1"
cw20 = "1.0.1"
lib = { path = "./packages/lib" }
serde_json = { version = "1.0.64", features = ["preserve_order"] }
