[workspace]
members = [
    "contracts/cw-juicer",
    "contracts/whirlwind-swap",
    "packages/*",
]

[workspace.dependencies]
cosmwasm-bignumber = "2.2.0"
cw2 = "1.0.1"
lib = { path = "./packages/lib" }
