[workspace]
members = [
    "contracts/cw-juicer",
    "contracts/whirlwind-swap",
    "packages/lib",
    "generate-data"
]

[workspace.dependencies]
cosmwasm-bignumber = "2.2.0"
cw2 = "1.0.1"
cw20 = "1.0.1"
lib = { path = "./packages/lib" }
