# [package]
# name = "whirlwind"
# version = "0.1.0"
# authors = ["Max Wu <chengmaxwu@gmail.com>"]
# edition = "2021"

[workspace]
resolver = "2"
members = [
    "contracts/cw-juicer",
    "packages/*",
]

[workspace.dependencies]
cw-juicer = { path = "contracts/cw-juicer" }
