# [package]
# name = "whirlwind"
# version = "0.1.0"
# authors = ["Max Wu <chengmaxwu@gmail.com>"]
# edition = "2021"

[workspace]
members = [
    "contracts/cw-juicer",
    # "contracts/whirlwind-swap",
    "packages/*",
]

[workspace.dependencies]
lib = { path = "./packages/lib" }
